"""
Contains countries' dictionary with their indices and year list.
"""

__all__ = [
    "countries_names",
    "years"
    ]

countries_names = {
    "Afghanistan"	: ("Afghanistan", 0),
    "Albania"		: ("Albania", 1),
    "Algeria"		: ("Algeria", 2),
    "Andorra"		: ("Andorra", 3),
    "Angola"		: ("Angola", 4),
    "Antigua "
    "and Barbuda"	: ("Antigua_and_Barbuda", 5),
    "Argentina"		: ("Argentina", 6),
    "Armenia"		: ("Armenia", 7),
    "Australia"		: ("Australia", 8),
    "Austria"		: ("Austria", 9),
    "Azerbaijan"	: ("Azerbaijan", 10),
    "Bahamas"		: ("Bahamas", 11),
    "Bahrain"		: ("Bahrain", 12),
    "Bangladesh"	: ("Bangladesh", 13),
    "Barbados"		: ("Barbados", 14),
    "Belarus"		: ("Belarus", 15),
    "Belgium"		: ("Belgium", 16),
    "Belize"		: ("Belize", 17),
    "Benin"		: ("Benin", 18),
    "Bhutan"		: ("Bhutan", 19),
    "Bolivia "
    "(Plurinational "
    "State of)"		: ("Bolivia", 20),
    "Bosnia "
    "Herzegovina"	: ("Bosnia_Herzegovina", 21),
    "Botswana"		: ("Botswana", 22),
    "Brazil"		: ("Brazil", 23),
    "Brunei "
    "Darussalam"	: ("Brunei", 24),
    "Bulgaria"		: ("Bulgaria", 25),
    "Burkina Faso"	: ("Burkina_Faso", 26),
    "Burundi"		: ("Burundi", 27),
    "Cabo Verde"	: ("Cabo_Verde", 28),
    "Cambodia"		: ("Cambodia", 29),
    "Cameroon"		: ("Cameroon", 30),
    "Canada"		: ("Canada", 31),
    "Central "
    "African Rep."	: ("Central_African_Republic", 32),
    "Chad"		: ("Chad", 33),
    "Chile"		: ("Chile", 34),
    "China"		: ("China", 35),
    "Colombia"		: ("Colombia", 36),
    "Comoros"		: ("Comoros", 37),
    "Congo"		: ("Congo", 38),
    "Costa Rica"	: ("Costa_Rica", 39),
    "Côte d\'Ivoire"	: ("Cote_D_Ivoire", 40),
    "Croatia"		: ("Croatia", 41),
    "Cuba"		: ("Cuba", 42),
    "Cyprus"		: ("Cyprus", 43),
    "Czechia"		: ("Czechia", 44),
    "Dem. Rep. of "
    "the Congo"		: ("Democratic_Republic_of_Congo", 45),
    "Denmark"		: ("Denmark", 46),
    "Djibouti"		: ("Djibouti", 47),
    "Dominica"		: ("Dominica", 48),
    "Dominican Rep."	: ("Dominican_Republic", 49),
    "Ecuador"		: ("Ecuador", 50),
    "Egypt"		: ("Egypt", 51),
    "El Salvador"	: ("El_Salvador", 52),
    "Equatorial "
    "Guinea"		: ("Equatorial_Guinea", 53),
    "Eritrea"		: ("Eritrea", 54),
    "Estonia"		: ("Estonia", 55),
    "Eswatini"		: ("Eswatini", 56),
    "Ethiopia"		: ("Ethiopia", 57),
    "Fiji"		: ("Fiji", 58),
    "Finland"		: ("Finland", 59),
    "France"		: ("France", 60),
    "Gabon"		: ("Gabon", 61),
    "Gambia"		: ("Gambia", 62),
    "Georgia"		: ("Georgia", 63),
    "Germany"		: ("Germany", 64),
    "Ghana"		: ("Ghana", 65),
    "Greece"		: ("Greece", 66),
    "Grenada"		: ("Grenada", 67),
    "Guatemala"		: ("Guatemala", 68),
    "Guinea"		: ("Guinea", 69),
    "Guinea "
    "Bissau"		: ("Guinea_Bissau", 70),
    "Guyana"		: ("Guyana", 71),
    "Haiti"		: ("Haiti", 72),
    "Honduras"		: ("Honduras", 73),
    "Hungary"		: ("Hungary", 74),
    "Iceland"		: ("Iceland", 75),
    "India"		: ("India", 76),
    "Indonesia"		: ("Indonesia", 77),
    "Iran"		: ("Iran", 78),
    "Iraq"		: ("Iraq", 79),
    "Ireland"		: ("Ireland", 80),
    "Israel"		: ("Israel", 81),
    "Italy"		: ("Italy", 82),
    "Jamaica"		: ("Jamaica", 83),
    "Japan"		: ("Japan", 84),
    "Jordan"		: ("Jordan", 85),
    "Kazakhstan"	: ("Kazakhstan", 86),
    "Kenya"		: ("Kenya", 87),
    "Kiribati"		: ("Kiribati", 88),
    "Kuwait"		: ("Kuwait", 89),
    "Kyrgyzstan"	: ("Kyrgyzstan", 90),
    "Lao People's "
    "Dem. Rep."		: ("Laos", 91),
    "Latvia"		: ("Latvia", 92),
    "Lebanon"		: ("Lebanon", 93),
    "Lesotho"		: ("Lesotho", 94),
    "Liberia"		: ("Liberia", 95),
    "Libya"		: ("Libya", 96),
    "Lithuania"		: ("Lithuania", 97),
    "Luxembourg"	: ("Luxembourg", 98),
    "Madagascar"	: ("Madagascar", 99),
    "Malawi"		: ("Malawi", 100),
    "Malaysia"		: ("Malaysia", 101),
    "Maldives"		: ("Maldives", 102),
    "Mali"		: ("Mali", 103),
    "Malta"		: ("Malta", 104),
    "Marshall "
    "Isds"		: ("Marshall_Islands", 105),
    "Mauritania"	: ("Mauritania", 106),
    "Mauritius"		: ("Mauritius", 107),
    "Mexico"		: ("Mexico", 108),
    "FS Micronesia"	: ("Micronesia", 109),
    "Rep. of "
    "Moldova"		: ("Moldova", 110),
    "Mongolia"		: ("Mongolia", 111),
    "Montenegro"	: ("Montenegro", 112),
    "Morocco"		: ("Morocco", 113),
    "Mozambique"	: ("Mozambique", 114),
    "Myanmar"		: ("Myanmar", 115),
    "Namibia"		: ("Namibia", 116),
    "Nepal"		: ("Nepal", 117),
    "Netherlands"	: ("Netherlands", 118),
    "New Zealand"	: ("New_Zealand", 119),
    "Nicaragua"		: ("Nicaragua", 120),
    "Niger"		: ("Niger", 121),
    "Nigeria"		: ("Nigeria", 122),
    "Dem. People's "
    "Rep. of Korea"	: ("North_Korea", 123),
    "North "
    "Macedonia"		: ("North_Macedonia", 124),
    "Norway"		: ("Norway", 125),
    "Oman"		: ("Oman", 126),
    "Pakistan"		: ("Pakistan", 127),
    "Palau"		: ("Palau", 128),
    "Panama"		: ("Panama", 129),
    "Papua New "
    "Guinea"		: ("Papua_New_Guinea", 130),
    "Paraguay"		: ("Paraguay", 131),
    "Peru"		: ("Peru", 132),
    "Philippines"	: ("Philippines", 133),
    "Poland"		: ("Poland", 134),
    "Portugal"		: ("Portugal", 135),
    "Qatar"		: ("Qatar", 136),
    "Romania"		: ("Romania", 137),
    "Russian "
    "Federation"	: ("Russia", 138),
    "Rwanda"		: ("Rwanda", 139),
    "Saint Kitts "
    "and Nevis"		: ("Saint_Kitts_and_Nevis", 140),
    "Saint "
    "Lucia"		: ("Saint_Lucia", 141),
    "Saint "
    "Vincent and "
    "the Grenadines"	: ("Saint_Vincent_and_the_Grenadines",
    					142),
    "Samoa"		: ("Samoa", 143),
    "San Marino"	: ("San_Marino", 144),
    "Sao Tome "
    "and Principe"	: ("Sao_Tome_and_Principe", 145),
    "Saudi Arabia"	: ("Saudi_Arabia", 146),
    "Senegal"		: ("Senegal", 147),
    "Serbia"		: ("Serbia", 148),
    "Seychelles"	: ("Seychelles", 149),
    "Sierra Leone"	: ("Sierra_Leone", 150),
    "Singapore"		: ("Singapore", 151),
    "Slovakia"		: ("Slovakia", 152),
    "Slovenia"		: ("Slovenia", 153),
    "Solomon Isds"	: ("Solomon_Islands", 154),
    "Somalia"		: ("Somalia", 155),
    "South Africa"	: ("South_Africa", 156),
    "Rep. of Korea"	: ("South_Korea", 157),
    "South Sudan"	: ("South_Sudan", 158),
    "Spain"		: ("Spain", 159),
    "Sri Lanka"		: ("Sri_Lanka", 160),
    "Sudan"		: ("Sudan", 161),
    "Suriname"		: ("Suriname", 162),
    "Sweden"		: ("Sweden", 163),
    "Switzerland"	: ("Switzerland", 164),
    "Syria"		: ("Syria", 165),
    "Tajikistan"	: ("Tajikistan", 166),
    "United Rep. "
    "of Tanzania"	: ("Tanzania", 167),
    "Thailand"		: ("Thailand", 168),
    "Timor-Leste"	: ("Timor_Leste", 169),
    "Togo"		: ("Togo", 170),
    "Tonga"		: ("Tonga", 171),
    "Trinidad "
    "and Tobago"	: ("Trinidad_and_Tobago", 172),
    "Tunisia"		: ("Tunisia", 173),
    "Turkey"		: ("Turkey", 174),
    "Turkmenistan"	: ("Turkmenistan", 175),
    "Tuvalu"		: ("Tuvalu", 176),
    "Uganda"		: ("Uganda", 177),
    "Ukraine"		: ("Ukraine", 178),
    "United Arab "
    "Emirates"		: ("United_Arab_Emirates", 179),
    "United Kingdom"	: ("United_Kingdom", 180),
    "Uruguay"		: ("Uruguay", 181),
    "USA"		: ("USA", 182),
    "Uzbekistan"	: ("Uzbekistan", 183),
    "Vanuatu"		: ("Vanuatu", 184),
    "Venezuela"		: ("Venezuela", 185),
    "Viet Nam"		: ("Vietnam", 186),
    "Yemen"		: ("Yemen", 187),
    "Zambia"		: ("Zambia", 188),
    "Zimbabwe"		: ("Zimbabwe", 189)
    }

years = [
    1996, 1997, 1998, 1999, 2000, 2001,
    2002, 2003, 2004, 2005, 2006, 2007,
    2008, 2009, 2010, 2011, 2012, 2013,
    2014, 2015, 2016, 2017, 2018
    ]
